package api

import (
	pb "KV-Store/proto" // Import the generated Proto code
	"KV-Store/raft"     // Import your Raft logic
	"context"
)

// RaftServer acts as the bridge.
// It implements the "RaftServiceServer" interface generated by gRPC.
type RaftServer struct {
	pb.UnimplementedRaftServiceServer            // Required by gRPC for forward compatibility
	rf                                *raft.Raft // Pointer to your actual Raft instance
}

// NewRaftServer creates the bridge
func NewRaftServer(rf *raft.Raft) *RaftServer {
	return &RaftServer{rf: rf}
}

// RequestVote is called by gRPC when another node asks for a vote
func (s *RaftServer) RequestVote(ctx context.Context, req *pb.RequestVoteRequest) (*pb.RequestVoteResponse, error) {
	// 1. Unpack Protobuf -> Go Struct
	args := &raft.RequestVoteArgs{
		Term:         int(req.Term),
		CandidateId:  int(req.CandidateId),
		LastLogIndex: int(req.LastLogIndex),
		LastLogTerm:  int(req.LastLogTerm),
	}
	var reply raft.RequestVoteReply

	// 2. Call your Raft Logic
	s.rf.RequestVote(args, &reply)

	// 3. Pack Go Struct -> Protobuf Response
	return &pb.RequestVoteResponse{
		Term:        int32(reply.Term),
		VoteGranted: reply.VoteGranted,
	}, nil
}

// AppendEntries is called by gRPC when the Leader sends logs/heartbeats
func (s *RaftServer) AppendEntries(ctx context.Context, req *pb.AppendEntriesRequest) (*pb.AppendEntriesResponse, error) {
	// 1. Unpack Protobuf -> Go Struct
	// We have to loop to convert the log entries slice
	var entries []raft.LogEntry
	for _, e := range req.Entries {
		entries = append(entries, raft.LogEntry{
			Term:    int(e.Term),
			Index:   int(e.Index),
			Command: e.Command,
		})
	}

	args := &raft.AppendEntriesArgs{
		Term:         int(req.Term),
		LeaderId:     int(req.LeaderId),
		PrevLogIndex: int(req.PrevLogIndex),
		PrevLogTerm:  int(req.PrevLogTerm),
		Entries:      entries,
		LeaderCommit: int(req.LeaderCommit),
	}
	var reply raft.AppendEntriesReply

	// 2. Call your Raft Logic
	s.rf.AppendEntries(args, &reply)

	// 3. Pack Go Struct -> Protobuf Response
	return &pb.AppendEntriesResponse{
		Term:    int32(reply.Term),
		Success: reply.Success,
	}, nil
}
